# packages in environment at /Users/gpfreitas/local/opt/miniconda3/envs/findata_py35:
#
anaconda-client           1.2.1                    py35_0    defaults
appnope                   0.1.0                    py35_0    defaults
astroid                   1.3.4                    py35_0    defaults
bokeh                     0.10.0                   py35_0    defaults
clyent                    1.2.0                    py35_0    defaults
cycler                    0.9.0                    py35_0    defaults
decorator                 4.0.4                    py35_0    defaults
flask                     0.10.1                   py35_1    defaults
freetype                  2.5.5                         0    defaults
ipykernel                 4.1.1                    py35_0    defaults
ipython                   4.0.1                    py35_0    defaults
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py35_0    defaults
ipython_genutils          0.1.0                    py35_0    defaults
itsdangerous              0.24                     py35_0    defaults
jinja2                    2.8                      py35_0    defaults
jsonschema                2.4.0                    py35_0    defaults
jupyter-client            4.1.1                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py35_0    defaults
jupyter_core              4.0.6                    py35_0    defaults
libpng                    1.6.17                        0    defaults
logilab-common            0.63.2                   py35_0    defaults
markupsafe                0.23                     py35_0    defaults
matplotlib                1.5.0               np110py35_0    defaults
mistune                   0.7.1                    py35_0    defaults
nbconvert                 4.0.0                    py35_0    defaults
nbformat                  4.0.1                    py35_0    defaults
notebook                  4.0.6                    py35_0    defaults
numpy                     1.10.2                   py35_0    defaults
openssl                   1.0.2d                        0    defaults
pandas                    0.17.1              np110py35_0    defaults
path.py                   8.1.2                    py35_1    defaults
pep8                      1.6.2                    py35_0    defaults
pexpect                   3.3                      py35_0    defaults
pickleshare               0.5                      py35_0    defaults
pip                       7.1.2                    py35_0    defaults
ptyprocess                0.5                      py35_0    defaults
pyflakes                  1.0.0                    py35_0    defaults
pygments                  2.0.2                    py35_0    defaults
pylint                    1.4.2                    py35_0    defaults
pyparsing                 2.0.3                    py35_0    defaults
pyqt                      4.11.4                   py35_1    defaults
python                    3.5.1                         0    defaults
python-dateutil           2.4.2                    py35_0    defaults
python.app                1.2                      py35_4    defaults
pytz                      2015.7                   py35_0    defaults
pyyaml                    3.11                     py35_1    defaults
pyzmq                     15.1.0                   py35_0    defaults
qt                        4.8.7                         1    defaults
readline                  6.2                           2    <unknown>
requests                  2.9.0                    py35_0    defaults
scipy                     0.16.1              np110py35_0    defaults
seaborn                   0.6.0               np110py35_0    defaults
setuptools                18.8.1                   py35_0    defaults
simplegeneric             0.8.1                    py35_0    defaults
sip                       4.16.9                   py35_0    defaults
six                       1.10.0                   py35_0    defaults
sqlite                    3.8.4.1                       1    <unknown>
terminado                 0.5                      py35_1    defaults
tk                        8.5.18                        0    <unknown>
tornado                   4.3                      py35_0    defaults
traitlets                 4.0.0                    py35_0    defaults
werkzeug                  0.11.2                   py35_0    defaults
wheel                     0.26.0                   py35_1    defaults
xz                        5.0.5                         0    <unknown>
yaml                      0.1.6                         0    <unknown>
zeromq                    4.1.3                         0    defaults
zlib                      1.2.8                         0    <unknown>
